<a href="https://colab.research.google.com/github/Mrigakshi24-ux/Training-Sheet/blob/main/SVD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Implementing SVD and reconstructing original matrix

In [7]:
import numpy as np
from numpy import array
from scipy.linalg import svd
from numpy import dot

In [20]:
A = array([[4, 5], [7, 8], [10, 11]])

In [21]:
# calculating U, S, V_t
U, S, V_t = svd(A)
print(U)
print(S)
print(V_t)

[[-0.33029839  0.85102074  0.40824829]
 [-0.54903267  0.17859579 -0.81649658]
 [-0.76776695 -0.49382916  0.40824829]]
[19.36119688  0.37954623]
[[-0.66329018 -0.7483623 ]
 [-0.7483623   0.66329018]]


In [23]:
# Reconstructing the A matrix from U, S, V_t
# S should be converted into a diagonal vector, but this new S matrix won't fit the multiplication
# we add a sigma matrix m*n and populate n*n values with S matrix

print(A.shape, U.shape, S.shape, V_t.shape, np.diag(S).shape)

# U(m*m).Sigma(m*n).V_t(n*n)

# sigma
sigma = np.zeros((A.shape[0], A.shape[1]))

# populate with S matrix, this complication only exist when not a square matrix
sigma[:A.shape[1], :A.shape[1]] = np.diag(S)   # A.shape[1] = n

# multiply
A = U.dot(sigma.dot(V_t))

(3, 2) (3, 3) (2,) (2, 2) (2, 2)


In [11]:
A # same as the input array.

array([[ 4.,  5.],
       [ 7.,  8.],
       [10., 11.]])

##SVD for dimensionality reduction

In [24]:
k = 3
A = array([[4, 5, 6, 7], [7, 8, 9, 10], [10, 11, 12, 13]])
U, S, V_t = svd(A)
print(A.shape, U.shape, S.shape, V_t.shape)
sigma = np.zeros((A.shape[0], A.shape[1]))
sigma[:S.shape[0], :S.shape[0]] = np.diag(S) 

# selecting k columns
sigma = sigma[:,:k]

# selecting k rows
V_t = V_t[:k, :]

# mutiply
B = U.dot(sigma.dot(V_t))
B

(3, 4) (3, 3) (3,) (4, 4)


array([[ 4.,  5.,  6.,  7.],
       [ 7.,  8.,  9., 10.],
       [10., 11., 12., 13.]])